name: 'GitHub Action Weather Bot'

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Weather Png'
        run: bash ./weather-png.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Xian' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Xian Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: Javen.Jin@outlook.com
          from: GitHub Actions
          content_type: text/html